### ISSUE TITLE
Improvement for not available variables

### ISSUE THREAD

**Issue by aleskozina** [swoodford/migrate_bitbucket_server_to_bitbucket_cloud#4]
Hey Dude

Thanks for your script, it really helped me and i saved a lot time to migrate my repos.

This is not actually a bug request, more of an improvement. Im not a bash specialist so i cannot make a PR with the fixes.

This two variables need to be present, otherwise following commands will fail:
- `LFSREPOS`
- `MIGRATEDREPOS`

Maybe helpfull:
- zsh 5.6.2 (x86_64-apple-darwin17.7.0)
- macOS Mojave, 10.14.2 (18C54)
- if you need anything else, tell me!

Again, thanks for your work!

Kind Regards
Ales

**Comment by swoodford** [comment]
Hey @aleskozina!  Thanks for letting me know, I'll take a look and see what's happening here.

**Comment by swoodford** [comment]
Hi @aleskozina would you please test this fix in cbab008?
